### PR TITLE
Create craftable-item-spawn-egg.md

### PR DESCRIPTION
**Pull request by Entitygamer66**
Added a turorial for bedrock wiki on how to make a craftable spawn eggs.

### CODE REVIEW

**Comment by SirLich** [comment]
Is this resurecting an old tutorial? It looks familiar.

**Comment by Entitygamer66** [comment]
nope, i just made my own tutorial for it.

**Comment by Entitygamer66** [comment]
> Is this resurecting an old tutorial? It looks familiar.

nope, this tutorial was made by me.

**Review by MedicalJewel105 — CHANGES_REQUESTED** [review]
Update item to work on latest MC version plus add files of images (they do in docs/public/...) instead of links.

**Pull request closed without merging**
