### PR TITLE
New Script Tutorial on Block Placement Prevention

### PR DESCRIPTION
**Pull request by JWForever5504**
I am a relatively new script user, and after trying for hours to find resources on how to prevent a block from being placed, I decided to create my own. I know this is probably pretty easy for most, but for newbies like myself, this resource could be very helpful.

I was made aware by a YouTuber that some dangerous unobtainable blocks are able to be acquired in 1.20.10, and created this to keep my server safer. I definitely want others to be able to do this to keep their servers safe.

### CODE REVIEW

**Comment by conmaster2112** [comment]
Its, pretty fine but every script api example or tutorial shouldn't include documentation to JS basic but should link the information where to find for example you explaining how if works, but you should link the JS Docs for if statement. Its not very related to script api. Thank for your time to contributing here.

**Comment by conmaster2112** [comment]
Hi, There are also small inaccuracies that can result in misunderstanding. For example:
> This is the main function to execute our commands. `world.beforeEvents.itemUseOn.subscribe()` will run before any item is used.

This is not main function, its method of specific event to subscribe for, that event will trigger your code, this specific event will trigger before that item is used on block.

**Comment by conmaster2112** [comment]
if you want to help with something let me know

> Hi, There are also small inaccuracies that can result in misunderstanding. For example:
> 
> > This is the main function to execute our commands. `world.beforeEvents.itemUseOn.subscribe()` will run before any item is used.
> 
> This is not main function, its method of specific event to subscribe for, that event will trigger your code, this specific event will trigger before that item is used on block.

**Comment by JWForever5504** [comment]
> if you want to help with something let me know
> 
> > Hi, There are also small inaccuracies that can result in misunderstanding. For example:
> > > This is the main function to execute our commands. `world.beforeEvents.itemUseOn.subscribe()` will run before any item is used.
> > 
> > 
> > This is not main function, its method of specific event to subscribe for, that event will trigger your code, this specific event will trigger before that item is used on block.

Yeah, I could definitely receive some help.

i don’t know much about how this all works, but if it’s possible to make modifications to my fork, and then explain them to me, I would very much appreciate it.

**Comment by conmaster2112** [comment]
Ok, give me some time, if that doesn't rush i have some IRL stuff, i will look at deeper later.

**Comment by JWForever5504** [comment]
> Ok, give me some time, if that doesn't rush i have some IRL stuff, i will look at deeper later.

Thank you so much for the help. You can also DM me on Discord. I joined the Bedrock OSS Discord, and my username is JWForever5504.

**Pull request merged**
