### PR TITLE
Rewrite dead links detection script from Python to JS

### PR DESCRIPTION
**Pull request by hvlxh**
I changed the language from python to javascript to detect the dead links.

### CODE REVIEW

**Comment by hvlxh** [comment]
i thought it gonna fail cause i change the file extension, probably the action test missing something

**Comment by hvlxh** [comment]
or not

**Comment by stirante** [comment]
Please edit the PR description to describe the changes. 

Don't hate on mixing languages. Dead links detection was written by Lich afaik and he feels more comfortable with python.

Also please don't treat PR comments as Discord

**Comment by SirLich** [comment]
Honestly the dead links script isn't needed at all. It's dead code. VitePress has an NPM target which we call `npm run build` which shows dead-links as errors, just like the CI build does. 

I was originally just using `npm run dev` which doesn't error on such simple issues, and thus I wrote a hacky Python script to lint my code.

**Pull request merged**
